version: 2.1

jobs:
  build:
    docker:
      - image: 'cimg/openjdk:11.0.6'
    steps:
      - checkout
      - run: 
          command: mvn clean install 
      - store_artifacts:
          path: '**/target/*.jar'
      - store_artifacts:
          path: '**/target/*.war'
      - store_test_results:
          path: target/surefire-reports

workflows:
  version: 2
  maven_test:
    jobs:
      - build:
            filters:
              branches:
                  only: feature/for_circleci
