version: 2.1

orbs:
  maven: circleci/maven@1.0.0

workflows:
  maven_test:
    jobs:
      - maven/test
          executor: '11.0.6'
      filters:
        branches:
      	  only: feature/for_circleci
