version: 2.1

orbs:
  maven: circleci/maven@1.0.0
  
jobs:
  build:
    docker:
      - image: 'cimg/openjdk:11.0.6'
    steps:
      - checkout
      - run: 
          command: mvn clean test 
      - store_artifacts:
          path: "**/target/*.ar"
      - store_test_results:
          path: "**/target/TEST**.xml"

workflows:
  version: 2
  maven_test:
    jobs:
      - build:
      	  filters:
      		branches:
      			only: feature/for_circleci
